server:
  address: ":8080"
log:
  level: "info"
debug: true
clusters:
  - name: "Homelab PVE"
    api_url: "https://pve01.srv.saminthedark.fr:8006"
    secret_id: "root@pam!dashboard"
    secret_token: "3b8ae6ac-0c68-48dd-b6b1-c4e1e36b6f0a"
